### ISSUE TITLE
i want to include contents only if a conditional is true

### ISSUE THREAD

**Issue by hagnat** [hagnat/yaml-parser#3]
- check if conditional is present and true
- if valid, includes the entity/file on the same level it was declared
- otherwise, ignores

# example
```yaml
foobar:
# valid conditional, entity included
  - !when: 1 == 1
    name: foo
# invalid condititional, entity not included
  - !when: 1 == 2
    name: bar
```
